### ISSUE TITLE
[模板] Wechaty 社区任务提交模板

### ISSUE THREAD

**Issue by rickyyin98** [wechaty/summer-of-code#1]
# 主题（一句话介绍）

## 需求介绍
介绍完整的需求背景，为什么需要这样的一个解决方案。  
在这个问题被解决之前是什么样的，问题被解决之后，能产生多大的变化。  

## 项目难度
高、中、低

## 导师联系方式
邮件、微信

### 核心目标
- 具体列出，当完成这些目标时，视为项目完整    

### 增量目标
- 除了基础的核心目标，还有哪些工作完成后将让项目更有价值  

## 项目技术栈  
- 需要使用哪些语言、框架、算法  

## 相关资料
- 对应项目的 Repo 链接、文档等

Link to #3  (Wechaty 社区暑期2020项目单)

**Comment by rickyyin98** [comment]
#可供参考的任务完整叙述

https://github.com/wechaty/summer-of-code/issues/2

**Comment by huan** [comment]
Close this issue because our Summer 2020 has been successfully completed!

Thanks for the hard works from @rickyyin98, I'm very appreciated!
