### ISSUE TITLE
基于开放 API 封装 Wechaty 接口下的飞书聊天机器人

### ISSUE THREAD

**Issue by rickyyin98** [wechaty/summer-of-code#12]
# 此次活动
## 开源软件供应链点亮计划
“开源软件供应链点亮计划-暑期2020”（以下简称 暑期2020）是由中科院软件所与 openEuler 社区共同举办的一项面向高校学生的暑期活动，旨在鼓励在校学生积极参与开源软件的开发维护，促进国内优秀开源软件社区的蓬勃发展。  
根据项目的难易程度和完成情况，参与者还可获取“开源软件供应链点亮计划-暑期2020”活动奖金和奖杯。
官网：https://isrc.iscas.ac.cn/summer2020 官方新闻：http://www.iscas.ac.cn/xshd2016/xshy2016/202004/t20200426_5563484.html

## Wechaty
Wechaty 是一个开源聊天机器人框架SDK，具有高度封装、高可用的特性，支持NodeJs, Python, Go 和Java 等多语言版本。在过去的4年中，服务了数万名开发者，收获了 Github 的 8000 Star。同时配置了完整的DevOps体系并持续按照Apache 的方式管理技术社区。

# 基于开放 API 封装 Wechaty 接口下的飞书聊天机器人

### 飞书提供开放的API接口，有基于开放API开发聊天机器人的需求
飞书是字节跳动于2016年自研的新一代一站式协作平台，是保障字节跳动全球五万人高效协作的办公工具。飞书将即时沟通、日历、云文档、云盘和工作台深度整合，通过开放兼容的平台，让成员在一处即可实现高效的沟通和流畅的协作，全方位提升企业效率。  
2020年2月24日，字节跳动旗下办公套件飞书宣布，向全国所有企业和组织免费开放，不限规模，不限使用时长，所有用户均可使用飞书全部套件功能。  
飞书官方提供API支持机器人收发消息，是国内对Chatbot最开放的IM 系统。  
### Wechaty是全球最大的开源聊天机器人框架，希望实现基于同一套应用层代码实现不同软件的聊天机器人
Wechaty 作为全球最大的聊天机器人开发者社区之一，提供了非常简单的接口实现，让开发者能够用6行代码就实现自己的一个聊天机器人，如果能把飞书的聊天机器人封装到 Wechaty 里来，则可以大大简化企业内开发者的开发流程。
因为 Wechaty 是建立在 puppet 系统之上的，puppet 是 Wechaty 依赖的一层抽象层，它定义了底层各个 IM 接入方案需要实现的接口，也正是因为 puppet 抽象层的存在，让很多 Wechaty 开发者可以仅仅通过一个变量，就能够随意切换不同的底层 IM 接入。

## 项目难度
高（奖金：12000元）

## 导师联系方式
- 高原：句子互动CTO、前亚马逊工程师（gaoyuan@juzi.bot）
- 李佳芮：句子互动CEO、专注微信生态近10年（rui@juzi.bot）

### 核心目标
飞书 puppet
- 通过飞书订阅消息事件读取消息
- 通过飞书订阅通讯录事件实时更新通讯录内成员信息
- 对接飞书接口，实现 puppet 上各个类型的消息接口
- 设计配置参数
- 飞书 puppet 的使用文档

## 项目技术栈  
- 了解 javascript 语言
- 有 typescript 语言的使用经验优先
- 熟练使用 Github 的优先
- 如果你的学习能力超强，可以无视上面的技术要求  

## 相关资料
- https://open.feishu.cn/document/ukTMukTMukTM/uUTNz4SN1MjL1UzM
- https://wechaty.js.org/v/zh/

Link to #3 (Wechaty 社区暑期2020项目单)

**Comment by Roxanne718** [comment]
# [基于开放 API 封装 Wechaty 接口下的飞书聊天机器人] 进度报告

日期：07-19

## 本周完成的成果
由于学校夏季学期的课程的安排，本周暂无成果

## 本周遇到的困难和需要配合的地方
控制台二维码乱码

## 下周的开发计划和预计成果
1. 解决控制台乱码问题，运行demo
2. 尝试通过飞书订阅消息事件读取消息

## 其他需要说明和同步的事项
暂无

**Comment by huan** [comment]
Could you please make a plan in more detail for our Summer of Code project, so that we can be better planned and track our progress better?

Plan in weeks and months, with a clear deliverable in the end would be acceptable.

**Comment by Roxanne718** [comment]
## [基于开放 API 封装 Wechaty 接口下的飞书聊天机器人]具体计划

- 导师：高原 吴京京
- 学生：范蕊
- 模块列表
  - [ ] 接收消息
  - [ ] 通讯录获取
  - [ ] 实现 puppet 上各个类型的消息接口
  - [ ] 设计配置参数
  - [ ] 使用文档
- 计划安排：
  - 阅读源代码
    - 7.29 - 7.31
    - 阅读 wechaty 源代码
    - 学习飞书服务端 API
    - 整理需要实现的 puppet list
  - 接收消息
    - 8.1 - 8.5
    - 通过飞书订阅消息事件实现消息接收
  - 通讯录获取
    - 8.6 - 8.10
    - 通过飞书订阅通讯录事件实现通讯录更新信息的接收
  - 实现 puppet 上各个类型的消息接口
    - 8.10 - 8.30
    - 对接飞书接口, 实现各个类型的消息接口
    - 消息类型包括: 文字, 图片, 富文本, 群名片
  - 设计配置参数
    - 8.31 - 9.7
  - 使用文档
    - 9.8 - 9.12
  - 项目完善
    - 9.12 - 9.30
    - 代码重构
- 项目链接：[https://github.com/Roxanne718/wechaty-puppet-lark](https://github.com/Roxanne718/wechaty-puppet-lark)
- 联系方式：+86 17822015718 | email: 953299708@qq.com

## 相关链接
- [飞书开放平台](https://open.feishu.cn/document/ukTMukTMukTM/uUTNz4SN1MjL1UzM)
- [Wechaty](https://wechaty.js.org/v/zh/)
- [Express](https://www.runoob.com/nodejs/nodejs-express-framework.html)
- [TypeScripts中文手册](https://www.tslang.cn/docs/handbook/basic-types.html)

**Comment by Roxanne718** [comment]
# [基于开放 API 封装 Wechaty 接口下的飞书聊天机器人] 进度报告

日期：08-02

## 本周完成的成果
- 了解飞书订阅事件流程，注册飞书应用程序
- 尝试使用Express搭建本地服务器，从而接收来自飞书的订阅事件

## 本周遇到的困难和需要配合的地方
- 运行 node 时遇到报错，暂未找到合适的解决办法
![image](https://user-images.githubusercontent.com/36890353/89126881-005b3780-d51c-11ea-9066-fbcaf617ab9d.png)

## 下周的开发计划和预计成果
- 完成飞书订阅事件的消息接收
- 搭建ding-dong-bot

## 其他需要说明和同步的事项
[项目地址](https://github.com/Roxanne718/wechaty-puppet-lark)

**Comment by windmemory** [comment]
> ## 本周遇到的困难和需要配合的地方
> * 运行 node 时遇到报错，暂未找到合适的解决办法

这个是 es6 的语法，并非nodejs的原生语法，所以没办法直接用nodejs调用。你可以在本地安装一下`typescript` 和 `ts-node` 来运行代码

```shell
npm i -g typescript ts-node
```

**Comment by Roxanne718** [comment]
> > ## 本周遇到的困难和需要配合的地方
> > 
> > * 运行 node 时遇到报错，暂未找到合适的解决办法
> 
> 这个是 es6 的语法，并非nodejs的原生语法，所以没办法直接用nodejs调用。你可以在本地安装一下`typescript` 和 `ts-node` 来运行代码
> 
> ```shell
> npm i -g typescript ts-node
> ```

谢谢老师，已解决

**Comment by Roxanne718** [comment]
# [基于开放 API 封装 Wechaty 接口下的飞书聊天机器人] 进度报告

日期：08-09

## 本周完成的成果
- 本地实现了消息接收
- 在本地搭建了飞书ding-dong机器人
![image](https://user-images.githubusercontent.com/36890353/89734280-c515b700-da8d-11ea-90bf-eba21be30840.png)

## 本周遇到的困难和需要配合的地方
- 原计划采用localtunnel实现内网穿透，但无论是在命令行使用还是在ts代码中使用，localtunnel都没有任何响应（不输出url），尝试在本地搭建localtunnel服务器，仍然没有响应。目前使用的是免费版ngrox，但每次启动时子域名都会发生变化。

## 下周的开发计划和预计成果
- 将ding-dong-bot迁移到飞书上
- 实现通讯录更新消息接收

## 其他需要说明和同步的事项
无

**Comment by huan** [comment]
Congratulations!

I have the solution to your `localtunnel` problem:

1. It does not work because the default server is not working anymore. (localtunnel.me)
1. You can use `localtunnel.chatie.io` for developing.

For example: use `ding-talk-development.localtunnel.chatie.io` with localtunnel, I believe it should work.

See: https://github.com/wechaty/wechaty-puppet-official-account/blob/master/src/official-account/official-account.spec.ts#L21

**Comment by Roxanne718** [comment]
> 2\. localtunnel.chatie.io

谢谢老师！问题解决了！

**Comment by huan** [comment]
Glad to know that, cheers!

**Comment by Roxanne718** [comment]
# [基于开放 API 封装 Wechaty 接口下的飞书聊天机器人] 进度报告

日期：08-17

## 本周完成的成果
- 实现了图片的发送和接收
![image](https://user-images.githubusercontent.com/36890353/90413961-bf4d5080-e0e1-11ea-81cb-ee95f8c0500a.png)

![image](https://user-images.githubusercontent.com/36890353/90413789-87dea400-e0e1-11ea-8e61-9d57268ec93e.png)
- 实现了企业通信录成员、部门列表的接收（尚未封装到puppet中）
- 实现了文件（包括视频）的接收（尚未封装到puppet中）

## 本周遇到的困难和需要配合的地方
- 每次重新运行项目时，Localtunnel的子域名就会失效，猜测是因为上一次的域名资源没有被正确释放，但还没找到解决方法
- 此外，在启动时，localtunnel有一定的几率报如下错误，不清楚是什么原因
![image](https://user-images.githubusercontent.com/36890353/90414430-5c0fee00-e0e2-11ea-9fae-ae80d68dc934.png)
代码在这里：
https://github.com/Roxanne718/wechaty-puppet-lark/blob/ea8371dde58ead9f17485b18144ac0752588cb6d/src/puppet-lark.ts#L70
- 对项目的一些细节不太确定，比如接收到图片后应该给用户暴露怎样的接口、图片是否要存储，以及`messageFile`，`messageImage`等函数内部应该实现什么功能等。

## 下周的开发计划和预计成果
- 实现文件（包括视频）的发送
- 将通讯录的接收、文件的接收封装到puppet中

## 其他需要说明和同步的事项
[项目地址](https://github.com/Roxanne718/wechaty-puppet-lark/)

**Comment by Roxanne718** [comment]
# [基于开放 API 封装 Wechaty 接口下的飞书聊天机器人] 进度报告

日期：08-30

## 本周完成的成果
- 将通讯录和文件的接收封装到puppet中
- 由于学校期末考试安排，本周进度较少

## 本周遇到的困难和需要配合的地方
-  无

## 下周的开发计划和预计成果
- 实现通讯录更新事件的获取

## 其他需要说明和同步的事项
[项目地址](https://github.com/Roxanne718/wechaty-puppet-lark/)

**Comment by Roxanne718** [comment]
# [基于开放 API 封装 Wechaty 接口下的飞书聊天机器人] 进度报告
日期：09-21

## 本周完成的成果
实现了群组的部分功能，包括创建群、解散群、获取群成员列表、获取群成员变化信息等。
## 本周遇到的困难和需要配合的地方
puppet.ts提供的函数和飞书支持的接口并不完全重合，对于不重合的部分应该怎么处理？
## 下周的开发计划和预计成果
发布npm包、根据飞书的要求限制机器人发信频率。
## 其他需要说明和同步的事项
无

**Comment by huan** [comment]
@rickyyin98 Thanks for the mentoring!

@Roxanne718 Thank you very much for joining the Wechaty open source project and finished Summer 2020 successfully!

You did an amazing job, and let's continue improving the wechaty-puppet-lark in 2021 together!
