### ISSUE TITLE
Wechaty SoC 微信群使用说明

### ISSUE THREAD

**Issue by rickyyin98** [wechaty/summer-of-code#18]
## 核心原则
Wechaty SoC活动期间，保持同时只有两个群：一个通知群、一个讨论群。
在不同阶段，两个群的人员有所不同，但持续遵循这一原则。

### Wechaty Summer of Code - SoC
- 其中包括本期活动入选同学、未入选同学、社区导师。
- 所有技术相关问题全部在此群内讨论，鼓励未入选同学也能以个人开发者的身份参与到对应项目中。
- 所有社区活动、沙龙分享等信息均在此群内向同学们同步。
- 后续SoC相关Issue和PR将会由OSS BOT转发到群中。
- 此群长期存在。
### Wechaty Summer of Code - Annouce
- 其中包括本期活动入选同学、社区导师。
- 此群非严格意义上的禁言，所有技术问题鼓励同学们在SoC群内讨论。
- 群内由社区工作人员同步活动奖金、提交代码规范、答辩规范等重要信息，并可针对这些问题进行讨论和答疑。
- 此群在暑期2020结束后解散。

### Wechaty Summer of Code - SoC
- 不同年份的入选同学、未入选同学、社区导师均共用此群。
- 每年 SoC 继续将其作为核心讨论群，不另外设置新群，旨在让往届校友同学也能参与提出意见或指导开发。
### Wechaty Summer of Code - Annouce
- 其中包括当期活动入选同学、社区导师。
- 在对应年份活动开始后新建，并在对应年份活动后解散。

**Comment by huan** [comment]
Thanks @rickyyin98 for drafting the rules of our SoW room!

Merged to README.
