### ISSUE TITLE
Soc Student blog progress Statistics

### ISSUE THREAD

**Issue by wj-Mcat** [wechaty/summer-of-code#20]
`SoC` 即将进入尾声，同学们已完成项目中大部分的功能模块，甚至开始提升项目在代码质量，添加CI/CD流程，进度都非常棒。为了方便大家查看自己在社区内完成的博客任务进度，我将罗列出各位同学在社区内不同阶段内的博客进度报告：

| 项目名称                                              | 学生名称 | 导师           | 计划书/初期报告 | 中期报告 | 结项报告 |
| ----------------------------------------------------- | -------- | -------------- | --------------- | -------- | -------- |
| [基于 RPA 封装 Wechaty  接口下的快手聊天机器人](https://github.com/bikaiqiao/kuaishouPuppet)         | 毕凯乔   | 王凯峰，尹伯昊 | ✅               | ✅        | ❌        |
| [基于RPA封装的Wechaty接口下的抖音聊天机器人](https://github.com/gavinwang23/wechaty-puppet-douyin)            | 王俊伟   | 王凯峰，尹伯昊 | ✅               | ✅        | ❌        |
| [基于开放 API 封装 Wechaty  接口下的企业微信聊天机器人](https://github.com/Sapio-S/wechaty-puppet-official/) | 谢昱清   | 高原，李佳芮   | ✅ + ☑           | ☑        | ✅        |
| [基于开放 API 封装 Wechaty  接口下的飞书聊天机器人](https://github.com/Roxanne718/wechaty-puppet-lark)     | 范蕊     | 高原，李佳芮   | ✅               | ✅       | ✅        |
| [基于开放 API 封装 Wechaty  接口下的钉钉聊天机器人](https://github.com/jihuayu/wechaty-puppet-dingtalk)     | 纪华裕   | 高原，李佳芮   | ✅               | ❌        | ✅        |
| [编写一个“每日一句”插件](https://github.com/univerone/WordsPerDay)                                | 江姗姗   | gcaufy         | ✅               | ✅        | ✅        |
| [为 go-wechaty 设计实现  插件体系](https://github.com/wechaty/go-wechaty/pull/67)                      | 林昊翰   | 丁小雨         | ✅               | ✅         | ✅         |
| [Go-wechaty Github  Action optimization](https://github.com/wechaty/go-wechaty)                | 唐光彬   | 丁小雨         | ✅               | ✅        | ✅        |
| [基于Python-wechaty建立一个斗图机器人](https://github.com/MrZilinXiao/python-wechaty-meme-bot/)                  | 肖梓霖   | 黄纯洪         | ✅               | ✅        | ✅        |
| [基于python-wechaty的群聊助手机器人](https://github.com/kxz18/python-wechaty-groupchat-bot)                    | 孔祥哲   | 吴京京         | ✅               | ✅        | ✅          |
| [Wechaty Java 移植组件开发](https://github.com/cunkoulaocai/java-wechaty)                             | 陈炀     | 刁政欣         | ☑               | ☑        | ❌        |

此进度统计将会不断更新，如果同学们有任何疑问或信息展示不及时，可在此issue下方评论。

备注:

- ✅ ：代表着**已完成**
- ☑：代表着还在[**Pull request**](https://github.com/wechaty/wechaty.js.org/pulls) 当中躺着
- ❌：代表博客未找到

**Comment by huan** [comment]
Thank you very much @wj-Mcat for all the hard work pushing the Summer 2020 program moving forward!

This program can not be successful like today without you, appreciate it!
