### ISSUE TITLE
TODO List of SoC [wj-Mcat]

### ISSUE THREAD

**Issue by wj-Mcat** [wechaty/summer-of-code#25]
## 概述

此次去南京开源之旅整体很成功，向多个开源社区介绍了wechaty，并且还有很大的意愿去了解，尽管现场的人员数量并不是太多，可邀请进来的人质量都还是挺高的。

最后从客观的角度上而言，我们还有很多方面的事情可以做的更好，以提升以后社区参与活动的效果。接下来我将罗列接下来需要推进的事情

## TODO List

- [ ]  关于python-wechaty开源之旅博客
- [ ] 邀请更多的开发者加入wechaty社区共同探讨聊天机器人的话题

**Comment by wj-Mcat** [comment]
refer to : #25

**Comment by wj-Mcat** [comment]
#26

**Comment by huan** [comment]
I believe you have delivered the above Key Results:

1. [Python-Wechaty 南京开源峰会之旅](https://wechaty.js.org/2020/12/08/python-wechaty-open-source-journey/) 
2. Python Wechaty stars grow a lot ([link](https://github.com/wechaty/python-wechaty#stargazers-over-time))!

![image](https://user-images.githubusercontent.com/1361891/104127384-ca5c9200-539c-11eb-996a-ba9592bc47d8.png)

Please feel free to close this issue after you confirmed all KRs has been delivered, thanks!
