### ISSUE TITLE
Collect open source summit related videos and pictures

### ISSUE THREAD

**Issue by univerone** [wechaty/summer-of-code#28]
Collect videos(Captured by Dji and Talk videos) and relevant pictures, upload it to google drive

#26

**Comment by univerone** [comment]
官方回放视频：
链接: https://pan.baidu.com/s/1DTZ-JVTpKcJMHDNM1Q5VZA 提取码: sx3w

**Comment by univerone** [comment]
youtube视频链接：
吴京京-Multi-Wechaty SDK for Chatbot
https://youtu.be/ncSWIRtHyAo
李卓桓-Wechaty的开源之路
https://youtu.be/DMMGB-32LFM

**Comment by huan** [comment]
@univerone Thank you very much for uploading our talk video to YouTube!

Please add them to our Wechaty YouTube Playlist (https://www.youtube.com/playlist?list=PL8hd9KDTdarDXf_Rxtr8meKhxtgcXMInh) so that our community can find them easily on YouTube, thank you very much!

**Comment by huan** [comment]
Hi, @univerone , I'm wondering about that is there a video for your talk (优秀学生分享)?

**Comment by univerone** [comment]
> Hi, @univerone , I'm wondering about that is there a video for your talk (优秀学生分享)?

Yes, I will upload it on YouTube soon

**Comment by huan** [comment]
Great, that's awesome!

**Comment by huan** [comment]
I have embedded the talk video from @wj-Mcat to the blog post at <https://wechaty.js.org/2020/12/08/python-wechaty-open-source-journey/>, and embedded talk from myself in my blog post at <https://wechaty.js.org/2020/11/14/summer-2020-summit-talks/>

Thanks for all the efforts from our great team!
