### ISSUE TITLE
python-wechaty 自动化测试构建和发布

### ISSUE THREAD

**Issue by wj-Mcat** [wechaty/summer-of-code#5]
# 此次活动
## 开源软件供应链点亮计划
“开源软件供应链点亮计划-暑期2020”（以下简称 暑期2020）是由中科院软件所与 openEuler 社区共同举办的一项面向高校学生的暑期活动，旨在鼓励在校学生积极参与开源软件的开发维护，促进国内优秀开源软件社区的蓬勃发展。  
根据项目的难易程度和完成情况，参与者还可获取“开源软件供应链点亮计划-暑期2020”活动奖金和奖杯。
官网：https://isrc.iscas.ac.cn/summer2020 官方新闻：http://www.iscas.ac.cn/xshd2016/xshy2016/202004/t20200426_5563484.html

## Wechaty
Wechaty 是一个开源聊天机器人框架SDK，具有高度封装、高可用的特性，支持NodeJs, Python, Go 和Java 等多语言版本。在过去的4年中，服务了数万名开发者，收获了 Github 的 8000 Star。同时配置了完整的DevOps体系并持续按照Apache 的方式管理技术社区。

# python-wechaty 自动化测试构建和发布

## 需求介绍

开源项目在不断迭代更新的过程中会存在很多的单元测试，项目构建和版本发布等任务，而这一系列的操作过程如果使用人力来完成的话，会存在大量的劳动力浪费，故需要一个自动化测试构建和发布的工具，而这个工具简称为CI/CD。Github有一套很完备的工具来完成这个过程。

此次的项目主要是为`python-wechaty`开发一套Github自动化测试，构建和发布的流程。

## 项目难度

中（奖金：9000元）

## 导师联系

- 吴京京：Wechaty Committer，Python Wechaty Author  1435130236@qq.com

## 项目产出目标

- 1.每次提交代码都需要完成单元测试和项目构建等步骤。
- 2.代码提交到master分支之后，除单元测试和项目构建步骤，还会触发版本发布步骤。
- 3.pull request合并到master分支之后，除单元测试和项目构建步骤，还会触发版本发布步骤。
- 4.master分支上代码发生变动之后，能够自动化将新版本发布到pypi官网库中。

## 项目技术栈

- 了解python如何打包发布
- 对python语言有一定掌握优先
- 熟练使用Github者优先
- 对CI/CD熟悉者优先

## 相关资料

- https://github.com/features/actions
- https://www.redhat.com/zh/topics/devops/what-is-ci-cd

**Comment by huan** [comment]
@wj-Mcat Thank you very much for creating this task!

Let's move on and prepare the Google Summer of Code 2021 from now, cheers!
